import { initHeaderEl } from "./components/header";
import { initTituloEl } from "./components/titulo";
import { initH3El } from "./components/h3";
import { initSubTituloEl } from "./components/subtitulo";
import { initPEl } from "./components/p";
import { initH4El } from "./components/h4";
import { initInputName } from "./components/input";
import { initButton } from "./components/button-volver";
import { initFooter } from "./components/footer";
(function main() {
  initHeaderEl();
  initTituloEl();
  initH3El();
  initSubTituloEl();
  initPEl();
  initH4El();
  initInputName();
  initButton();
  initFooter();
})();
